# Generated by Django 4.2.14 on 2024-07-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serial_mouse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capture",
            name="filename",
        ),
        migrations.AddField(
            model_name="capture",
            name="image",
            field=models.ImageField(
                default="static/captures/default.jpg", upload_to="captures/"
            ),
            preserve_default=False,
        ),
    ]
